language: node_js
node_js: 10.0.0
git:
  quiet: true
  submodules: false
  depth: 1
cache: yarn
addons:
  ssh_known_hosts: blog.swnb.site
branches:
  only:
  - master
  - develop
jobs:
  include:
  - stage: build
    if: branch = develop
    env: PUBLIC_URL=/development/
    script: yarn build
  - stage: build
    if: branch = master
    script: yarn build
before_deploy:
  - openssl aes-256-cbc -K $encrypted_5406ae1910a4_key -iv $encrypted_5406ae1910a4_iv -in deploy_rsa.enc -out ./deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 ./deploy_rsa
  - ssh-add ./deploy_rsa
deploy:
  - provider: script
    skip_cleanup: true
    script: rsync --delete -avz --progress -e ssh ./build/ $static_host_path_dev
    on:
      branch: develop
  - provider: script
    skip_cleanup: true
    script: rsync --delete -avz --progress -e ssh ./build/ $static_host_path
    on:
      branch: master
notifications:
  email:
    recipients:
    - swnblovego@gmail.com
    on_success: never
    on_failure: always
