name: main config
on: [push]
jobs:
  build:
    name: echo
    runs-on: ubuntu-latest
    steps: 
    - uses: ./echo-action
      with:
        who: "Some body"
      id: "id"
    - run: echo "project init"

